export { default as IMG_LogoTitle } from './IMG_LogoTitle.png';
export { default as IMG_BannerSample } from './IMG_BannerSample.png';
export { default as Book_Tickets } from './Book_Tickets.png';
export { default as Ellipse_1 } from './Ellipse_1.png';
export { default as Ellipse_2 } from './Ellipse_2.png';
export { default as Book_Tickets_IMG1 } from './Book_Tickets_IMG1.png';
export { default as Book_Tickets_IMG2 } from './Book_Tickets_IMG2.png';
export { default as Book_Tickets_IMG3 } from './Book_Tickets_IMG3.png';
export { default as Book_Tickets_IMG4 } from './Book_Tickets_IMG4.png';
export { default as Upcoming_Movies  } from './Upcoming_Movies.png';
export { default as Upcoming_Movies_IMG  } from './Upcoming_Movies_IMG.png';
export { default as Maaveeran} from './Maaveeran.png';
export { default as Line} from './Line.png';
export { default as Cast1} from './cast1.png';
export { default as Cast2} from './cast2.png';
export { default as Cast3} from './cast3.png';
export { default as Rating1} from './Rating.png';
export { default as logo} from './logo.png';
export { default as bottomtitle} from './bottomtitle.png';
export { default as Ellipse} from './Ellipse.png';
export { default as Line1} from './Line1.png';

