export { default as Login } from './02Login';
export { default as LogoMVT } from './01LogoMVT';
export { default as InputNumber } from './04InputNumber';
export { default as AfterLogin } from './03AfterLogin/';
export { default as OTPNumber } from './05OTPNumber';
export { default as ChoseCity } from './06ChoseCity';
export { default as Mainmenu } from './07Mainmenu';
export { default as ChooseOption } from './08ChooseOption';
export { default as TabRouter } from './../router/TabRouter';
